# SPEAR Platform Support
obj-$(CONFIG_SND_SPEAR_SOC) += spear13xx_pcm.o
obj-$(CONFIG_SND_DESIGNWARE_I2S) += designware_i2s.o
obj-$(CONFIG_SND_SPEAR_SPDIF_OUT) += spdif_out.o

# SPEAR Machine Support
obj-$(CONFIG_SND_SPEAR13XX_EVM) += spear13xx_evb.o
