# SPEAR Platform Support
obj-$(CONFIG_SND_SPEAR_SOC) += spear13xx_pcm.o
obj-$(CONFIG_SND_DESIGNWARE_I2S) += designware_i2s.o

# SPEAR Machine Support
obj-$(CONFIG_SND_SPEAR_SOC_EVM) += spear13xx_evb.o
