#
# SPEAr Platform specific Makefile
#

# Common support
obj-y	:= clock.o time.o

obj-$(CONFIG_ARCH_SPEAR3XX)	+= shirq.o padmux.o
obj-$(CONFIG_SPEAR_CLCD)	+= clcd.o

obj-$(CONFIG_MACH_SPEAR310)	+= plgpio.o
obj-$(CONFIG_MACH_SPEAR320)	+= plgpio.o
